version: '3.10.10'

services:
  web:
    build: ../askme_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - askme_django/.env
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=askme_django
      - POSTGRES_PASSWORD=askme_django
      - POSTGRES_DB=askme_django_dev
    ports:
      - 5431:5432

volumes:
  postgres_data:
