# Generated by Django 4.2 on 2023-04-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_app', '0004_remove_tag_question_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
