# Generated by Django 4.2 on 2023-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_app', '0005_alter_vote_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
