# Generated by Django 4.2 on 2023-04-14 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme_app', '0008_alter_tag_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
