# Generated by Django 4.2 on 2023-06-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_app', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no-profile-picture-icon.png', upload_to='avatars'),
        ),
    ]
